### ISSUE TITLE
KeyError: 'response_track_valid_range'

### ISSUE THREAD

**Issue by fb-reps** [hwjiang1510/VQLoC#7]
Hello, 
This is a great work.
But I can't find key  'response_track_valid_range'  in any json file. 

I see that you seem to generate train_anno_new.json and val_anno_new.json.
but I can not get them when I follow the readme step.

***

Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/UNT/bf0191/anaconda3/envs/vqloc2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/UNT/bf0191/anaconda3/envs/vqloc2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/UNT/bf0191/anaconda3/envs/vqloc2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/DATA-1/bingfanprojects/VQLoC/dataset/base_dataset.py", line 363, in __getitem__
    clip, clip_idxs, before_query = self.clip_reader(clip_path,
  File "/mnt/DATA-1/bingfanprojects/VQLoC/dataset/base_dataset.py", line 477, in read_frames_decord_balance
    frame_idxs = sample_frames_balance(num_frames, query_frame, frame_interval, sample, sampling)      # downsampled fps idxs, used to get bbox annotation
  File "/mnt/DATA-1/bingfanprojects/VQLoC/dataset/base_dataset.py", line 428, in sample_frames_balance
    anno_valid_idx_range = sample["response_track_valid_range"]
KeyError: 'response_track_valid_range'

**Comment by hwjiang1510** [comment]
I can find the key exists in train_anno_new.json
Are you parsing the data correctly?

![image](https://github.com/hwjiang1510/VQLoC/assets/32667116/86160e46-06c4-43fc-bf20-f76efe2a40dc)

**Comment by fb-reps** [comment]
Great. 
how can i get the train_anno_new.json.
I follow the  vqloc readme file to use vq2d json process, I get val_annot.json and train_annot.json, but not train_anno_new.json

**Comment by fb-reps** [comment]
Thank you. I got it.
